### ISSUE TITLE
About inference time

### ISSUE THREAD

**Issue by txytju** [zjhuang22/maskscoring_rcnn#1]
Thanks for your great work!
In your paper, speed and computation is mentioned as "Our MaskIoU head has about 0.39G FLOPs while Mask head has about 0.53G FLOPs for each proposal."
As fa as I known,  there should be at least 10 proposals for mask head in each image, so that's 3.9G and 5.3G for MaskIou and Mask head. However, ResNet-18 is about 2G, so why MaskIoU head didn't lead to slower inference? Thank you!

**Comment by zjhuang22** [comment]
> Thanks for your great work!
> In your paper, speed and computation is mentioned as "Our MaskIoU head has about 0.39G FLOPs while Mask head has about 0.53G FLOPs for each proposal."
> As fa as I known, there should be at least 10 proposals for mask head in each image, so that's 3.9G and 5.3G for MaskIou and Mask head. However, ResNet-18 is about 2G, so why MaskIoU head didn't lead to slower inference? Thank you!

Thanks for your attention. The testing times show that the computation cost of MaskIoU head in Mask Scoring R-CNN (including the whole network forwarding and post-processing) is negligible.
