### ISSUE TITLE
evaluation problem

### ISSUE THREAD

**Issue by Angzz** [zjhuang22/maskscoring_rcnn#12]
Hi, I want to ask when you evaluate with box AP, what's the score type you use, cls score or mask score. I just can not understand that if you use the mask score to evaluate box AP, the box AP must drop, but in your repo, the box AP nearly unchanged, so I think the results of box AP and mask AP shown come from two different scores, and you test twice?

**Comment by zjhuang22** [comment]
> Hi, I want to ask when you evaluate with box AP, what's the score type you use, cls score or mask score. I just can not understand that if you use the mask score to evaluate box AP, the box AP must drop, but in your repo, the box AP nearly unchanged, so I think the results of box AP and mask AP shown come from two different scores, and you test twice?

box AP come from cls score, mask AP comes from mask score. I only test once.
