### ISSUE TITLE
[Errno 2] No such file or directory: 'datasets/coco/annotations/instances_train2014.json',but  the file does exist.

### ISSUE THREAD

**Issue by pandamax** [zjhuang22/maskscoring_rcnn#14]
loading annotations into memory...
Traceback (most recent call last):
  File "tools/train_net.py", line 171, in <module>
    main()
  File "tools/train_net.py", line 164, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 60, in train
    start_iter=arguments["iteration"],
  File "/home/yg/github/maskscoring_rcnn/maskrcnn_benchmark/data/build.py", line 149, in make_data_loader
    datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train)
  File "/home/yg/github/maskscoring_rcnn/maskrcnn_benchmark/data/build.py", line 41, in build_dataset
    dataset = factory(**args)
  File "/home/yg/github/maskscoring_rcnn/maskrcnn_benchmark/data/datasets/coco.py", line 13, in __init__
    super(COCODataset, self).__init__(root, ann_file)
  File "/home/yg/anaconda3/envs/ms-rcnn/lib/python3.5/site-packages/torchvision/datasets/coco.py", line 97, in __init__
    self.coco = COCO(annFile)
  File "/home/yg/anaconda3/envs/ms-rcnn/lib/python3.5/site-packages/pycocotools-2.0-py3.5-linux-x86_64.egg/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/yg/datasets/coco/annotations/instances_train2014.json'

and it seems that the same problem occurred in maskrcnn-benchmark
[https://github.com/facebookresearch/maskrcnn-benchmark/issues/345](url)

**Comment by Jason-xin** [comment]
Firstly, https://github.com/matterport/Mask_RCNN#ms-coco-requirements
Secondly, https://github.com/zjhuang22/maskscoring_rcnn#prepare-data

**Comment by celabi** [comment]
I have the same problem and I had try to use 'You need to pass the path to coco as the --dataset argument,
/path/to/coco/ has to become /home/mson/download/Mask_RCNN/coco, which gives you

python coco.py train --dataset=/home/mson/download/Mask_RCNN/coco --model=coco' but it said cannot import name 'mask' from'__main__'

**Comment by maomaochongchh** [comment]
@Jason-xin @celabi have you solved that error?

**Comment by celabi** [comment]
> @Jason-xin @celabi have you solved that error?



> loading annotations into memory...
> Traceback (most recent call last):
> File "tools/train_net.py", line 171, in 
> main()
> File "tools/train_net.py", line 164, in main
> model = train(cfg, args.local_rank, args.distributed)
> File "tools/train_net.py", line 60, in train
> start_iter=arguments["iteration"],
> File "/home/yg/github/maskscoring_rcnn/maskrcnn_benchmark/data/build.py", line 149, in make_data_loader
> datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train)
> File "/home/yg/github/maskscoring_rcnn/maskrcnn_benchmark/data/build.py", line 41, in build_dataset
> dataset = factory(**args)
> File "/home/yg/github/maskscoring_rcnn/maskrcnn_benchmark/data/datasets/coco.py", line 13, in **init**
> super(COCODataset, self).**init**(root, ann_file)
> File "/home/yg/anaconda3/envs/ms-rcnn/lib/python3.5/site-packages/torchvision/datasets/coco.py", line 97, in **init**
> self.coco = COCO(annFile)
> File "/home/yg/anaconda3/envs/ms-rcnn/lib/python3.5/site-packages/pycocotools-2.0-py3.5-linux-x86_64.egg/pycocotools/coco.py", line 84, in **init**
> dataset = json.load(open(annotation_file, 'r'))
> FileNotFoundError: [Errno 2] No such file or directory: '/home/yg/datasets/coco/annotations/instances_train2014.json'
> 
> and it seems that the same problem occurred in maskrcnn-benchmark
> [https://github.com/facebookresearch/maskrcnn-benchmark/issues/345](url)

When I downgraded the platform to 16.04 , pytorch=9.0 stable ,there is no error in here.

**Comment by zhuliqian** [comment]
have you solved that error? @maomaochongchh

**Comment by lapetite123** [comment]
Does anyone solved the problem?  I met the same problem but I failed to solve it

**Comment by PumayHui** [comment]
I have met the same problem as above, and I solved with such procedure. 
In addition, I have used my own dataset as coco.

Change the lines 7~23 in "maskscoring_rcnn/maskrcnn_benchmark/config/paths_catalog.py", then modify the path as your coco json files.

As I changed before:
`
class DatasetCatalog(object):
    DATA_DIR = "datasets"
    DATASETS = {
        "coco_2014_train": (
            "coco/train2014",
            "coco/annotations/instances_train2014.json",
        ),
        "coco_2014_val": ("coco/val2014", "coco/annotations/instances_val2014.json"),
        "coco_2014_minival": (
            "coco/val2014",
            "coco/annotations/instances_minival2014.json",
        ),
        "coco_2014_valminusminival": (
            "coco/val2014",
            "coco/annotations/instances_valminusminival2014.json",
        ),
    }
`
Changes after:
`
class DatasetCatalog(object):
    DATA_DIR = "datasets"
    DATASETS = {
        "coco_2014_train": (
            "coco/train2014",
            "coco/annotations/instances_train2014.json",
        ),
        "coco_2014_val": ("coco/val2014", "coco/annotations/instances_val2014.json"),
        "coco_2014_minival": (
            "coco/val2014",
            "coco/annotations/instances_val2014.json",
        ),
        "coco_2014_valminusminival": (
            "coco/val2014",
            "coco/annotations/instances_val2014.json",
        ),
    }
`

**Comment by zhuliqian** [comment]
When ln, it shows that the path does not exist, so the ln fails. Then, I put  files in a new folder and finds the path successfully.

How to modify the number of categories

**Comment by WZHsmile** [comment]
coco/**images**/val2014  Maybe you lost sth

**Comment by TheLostIn** [comment]
Maybe you entered the wrong directory.
For me,I've created a project directory and I've cloned the maskrcnn repository in it.And then I installed the maskrcnn environment following the commands in README.md,and also I'created another maskrcnn directory.And as I entered the previous directory to run the train command,I got the error'cannot import _C'.By accident ,I came back to the later directory,it worked well.Amazing!

**Comment by Qianyu-Z** [comment]
> Does anyone solved the problem? I met the same problem but I failed to solve it
have you sloved that？
