### ISSUE TITLE
Confusion about the procedure of inference

### ISSUE THREAD

**Issue by Wuziyi616** [zjhuang22/maskscoring_rcnn#20]
Hi, nice job man. But I'm still a little confused about the procedure of inference. In the original version of Mask-RCNN, NMS is processed among the proposals from RPN, and then the model use the rest proposals to generate cls-score and bbox-refinement. After that, another NMS is processed among the detections from cls-head and bbox-head. Finally, we feed the rest bbox to the mask-head and get the final result.
However, according to your paper, the mask-scores are used to refine the scores of cls-head, which means we should first get the mask-head outputs and then attach them to the cls-head. I'm just confused that how can the refined-scores help? Do you use those refined-scores to redo NMS among the detections from cls-head and -bbox-head and then re-feed them to mask-head to get some new segmentation results? So if I were correct, you had run the mask-head twice to get more accurate results?

**Comment by zjhuang22** [comment]
Thanks for your attention. We do not use the refined-scores to redo NMS. We only run the mask-head once. We use the mask-head output and feed them to the maskiou head to predict the maskiou. And then use the predicted maskiou multiply with cls score to get the final score.

**Comment by Wuziyi616** [comment]
Thanks for your answer. So the boost of performance is because that the target of mask-segmentation and predicting the correct IoU of masks are the same, and the network learns to extract more efficient and accurate features via training the mask-scoring head. Is my understanding correct?

**Comment by zjhuang22** [comment]
The boost of performance is mainly because using the predicting IoU correcting the score. The mask-segmentation results are unchanged.

**Comment by Wuziyi616** [comment]
ok I see. Thanks for your kind answers!
