### ISSUE TITLE
Can you provide a jupyter notebook demo?

### ISSUE THREAD

**Issue by YubinXie** [zjhuang22/maskscoring_rcnn#27]
Hi,

Thank you for your works! It would be really beneficial for everyone who are interested in the model to have a notebook example that can do prediction based on COCO data on given images like what the original repo does.   
https://github.com/facebookresearch/maskrcnn-benchmark/tree/master/demo 

Thanks!

**Comment by YubinXie** [comment]
I have transferred demo from the original repo, however, due to lack of trained weights, the prediction is random.

@zjhuang22 Can you provide the trained weights from the paper (one is enough) so that we can provide a demo for others. Thanks!

**Comment by zjhuang22** [comment]
I've put the trained model in the corresponding link.

**Comment by YubinXie** [comment]
Did you refer to the pre trained model you shared before? I tested it and it gave random results. I am sure that model is pre-train model before your training.

**Comment by zjhuang22** [comment]
No. I have put the model weight after training in the corresponding link which can be found in README.

**Comment by YubinXie** [comment]
Oh, it just appeared! Thank you so much!!!

**Comment by YubinXie** [comment]
@zjhuang22 After testing on natural images, the trained model works. Thank you again for contributing.

The test results on most images look similar to the original method. Can you share some images that this method beats the original ones? Thanks!

**Comment by zjhuang22** [comment]
Thanks for your attention. Our approach is mainly to provide a higher quality score without improving the quality of masks or boxes. So the difference is on the score.

**Comment by YubinXie** [comment]
A jupyter notebook demo:
1. Move demo notebook, predictor.py to maskscoring_rcnn_master director (not demo folder)

2. Omit the keypoint parts in predictor.py since here keypoint is not supported.

2. download author's trained model (file ended with .pth) and put it to pre-trained folder.

3. modify the yaml file: update the model wieght path.

4. I remember moved some other scripts from original repo to make the demo notebook work. If you have import related error, just move the coressponding scripts to new repo.

**Comment by zjhuang22** [comment]
Thank you for your support for our project!

**Comment by 13012476909** [comment]
> A jupyter notebook demo:
> 
> 1. Move demo notebook, predictor.py from the original repo to this maskscoring_rcnn_master folder (not demo folder)
> 2. Omit the keypoint parts in predictor.py since here keypoint is not supported.
> 3. Download author's trained model (file ended with .pth) and put it to pre-trained folder.
> 4. Modify the yaml file: update the model wieght path.
> 5. I remember moved some other scripts from original repo to make the demo notebook work. If you have import related error, just move the corresponding scripts to this new repo.
> 6. PS: given most libraries in this repo has the same name as the old one, they have conflicts. In my experience, if you want to run this repo, you need to install it to your path before you run (the old one will be replaced.)

I want to know how the model weights should be modified.

**Comment by 13012476909** [comment]
> 4\. ht path.

WEIGHT: "pretrained_models/res50-model_0090000.pth"
Am I correct this way?

**Comment by YubinXie** [comment]
Right.

**Comment by 13012476909** [comment]
> Right.
Thank you

**Comment by 13012476909** [comment]
> 5\. I remember moved some other scripts from original repo to make the demo notebook work.

 File "maskscoring_rcnn-master/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: cannot import name '_C'
Then I moved all scripts from original repo to solve this problems, but it doesn't work.

**Comment by YubinXie** [comment]
Can't help on these details. But it seems to be an installation problem.

**Comment by yiming-lzx** [comment]
> > 5. I remember moved some other scripts from original repo to make the demo notebook work.
> 
> File "maskscoring_rcnn-master/maskrcnn_benchmark/layers/nms.py", line 3, in 
> from maskrcnn_benchmark import _C
> ImportError: cannot import name '_C'
> Then I moved all scripts from original repo to solve this problems, but it doesn't work.

First, did you compile the project with command "python setup.py build develop" and make it succeed. after that you will got an file name as "-C............". If not, you shall do it first.
Second, if you build it succeed. And still had the error problem, you can check your running environment, whether it is the compile environmen., if not, it can not run.So please change your environment and it will work.

**Comment by r-matsuzaka** [comment]
> A jupyter notebook demo:
> 
>     1. Move demo notebook, predictor.py from the original repo to this maskscoring_rcnn_master folder (not demo folder)
> 
>     2. Omit the keypoint parts in predictor.py since here keypoint is not supported.
> 
>     3. Download author's trained model (file ended with .pth) and put it to pre-trained folder.
> 
>     4. Modify the yaml file: update the model wieght path.
> 
>     5. I remember moved some other scripts from original repo to make the demo notebook work. If you have import related error, just move the corresponding scripts to this new repo.
> 
>     6. PS: given most libraries in this repo has the same name as the old one, they have conflicts. In my experience, if you want to run this repo, you need to install it to your path before you run (the old one will be replaced.)

Thank you very much.
I forked the repository and add the notebook feature.
https://github.com/r-matsuzaka/maskscoring_rcnn
