### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by Le0000000000n** [zjhuang22/maskscoring_rcnn#28]
I am trying to reproduce your work. When I run train_net I got this. BTW I am using coco2017 rather than coco2014. Is dataset selection related to this error?

Traceback (most recent call last):
  File "tools/train_net.py", line 171, in <module>
    main()
  File "tools/train_net.py", line 164, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "tools/train_net.py", line 53, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/root/github/maskscoring_rcnn/maskrcnn_benchmark/utils/checkpoint.py", line 61, in load
    checkpoint = self._load_file(f)
  File "/root/github/maskscoring_rcnn/maskrcnn_benchmark/utils/checkpoint.py", line 133, in _load_file
    return load_c2_format(self.cfg, f)
  File "/root/github/maskscoring_rcnn/maskrcnn_benchmark/utils/c2_model_loading.py", line 155, in load_c2_format
    return C2_FORMAT_LOADER[cfg.MODEL.BACKBONE.CONV_BODY](cfg, f)
  File "/root/github/maskscoring_rcnn/maskrcnn_benchmark/utils/c2_model_loading.py", line 146, in load_resnet_c2_format
    state_dict = _load_c2_pickled_weights(f)
  File "/root/github/maskscoring_rcnn/maskrcnn_benchmark/utils/c2_model_loading.py", line 124, in _load_c2_pickled_weights
    data = pickle.load(f, encoding="latin1")
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by zjhuang22** [comment]
I can run using coco2017. You may need to check in maskrcnn_benchmark/config/paths_catalog.py to make sure whether your modification is right. In addition, according to your reported errors, you need to check whether there is problem with pre-trained models.

**Comment by Le0000000000n** [comment]
> I can run using coco2017. You may need to check in maskrcnn_benchmark/config/paths_catalog.py to make sure whether your modification is right. In addition, according to your reported errors, you need to check whether there is problem with pre-trained models.

Hi! Thanks for your quick reply. I just updated datasets path in paths_catalog.py but same error still occurs. May I ask what do you mean by "problem with pre-pretrained models"? Do I need to download pertained resnet before hand?

**Comment by zjhuang22** [comment]
Yes, you need to download pre-trained models first. Please refer to README for more details.

**Comment by Le0000000000n** [comment]
> Yes, you need to download pre-trained models first. Please refer to README for more details.

Thanks. I was actually following README but still got bit confused. May I ask what specifically in paths_catalog.py needs to be changed to my own directory?

**Comment by zjhuang22** [comment]
If you use coco2017, you need to modify the dataset from coco2014 to coco2017.

**Comment by Le0000000000n** [comment]
> If you use coco2017, you need to modify the dataset from coco2014 to coco2017.

I did so. But same error still occurs.

**Comment by Le0000000000n** [comment]
Oh! problem solved! I forgot to put datasets folder under project folder. Thank you for your help!
