### ISSUE TITLE
What are instances_minival and instances_valminusminival?

### ISSUE THREAD

**Issue by Le0000000000n** [zjhuang22/maskscoring_rcnn#29]
Hi! I am using coco2017 dataset and have changed paths in paths_catalog from 2014 to corresponding 2017 ones. When I run the project I got this error:

No such file or directory: 'datasets/coco/annotations/instances_valminusminival2017.json'

It seems there is no such json file in coco datasets. May I ask what are these minival json files? How can I reproduce one?

**Comment by zjhuang22** [comment]
When you change the dataset from coco2014 to coco2017, you need to change the corresponding annotations too.     
 DATASETS = {
          "coco_2017_train": (
              "coco/train2017",
              "coco/annotations/instances_train2017.json",
          ),
          "coco_2017_val": (
              "coco/val2017",
              "coco/annotations/instances_val2017.json",
          ),
      }

**Comment by Le0000000000n** [comment]
Thanks!

**Comment by Elena-ssq** [comment]
> When you change the dataset from coco2014 to coco2017, you need to change the corresponding annotations too.
> DATASETS = {
> "coco_2017_train": (
> "coco/train2017",
> "coco/annotations/instances_train2017.json",
> ),
> "coco_2017_val": (
> "coco/val2017",
> "coco/annotations/instances_val2017.json",
> ),
> }

Hi. Where can I find this annotation?

**Comment by zjhuang22** [comment]
> > When you change the dataset from coco2014 to coco2017, you need to change the corresponding annotations too.
> > DATASETS = {
> > "coco_2017_train": (
> > "coco/train2017",
> > "coco/annotations/instances_train2017.json",
> > ),
> > "coco_2017_val": (
> > "coco/val2017",
> > "coco/annotations/instances_val2017.json",
> > ),
> > }
> 
> Hi. Where can I find this annotation?
> 
> In case this may help, I have solved this problem by referring to [this link](https://github.com/zjhuang22/maskscoring_rcnn/issues/14#issuecomment-479737839).

You can find here https://github.com/facebookresearch/Detectron/blob/master/detectron/datasets/data/README.md#coco-minival-annotations
