### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by zhuliqian** [zjhuang22/maskscoring_rcnn#31]
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 84 and 366 in dimension 0 at /opt/conda/conda-bld/pytorch_1549628766161/work/aten/src/THC/generic/THCTensorMath.cu:83

**Comment by zjhuang22** [comment]
Could you please provide more error information?

**Comment by zjhuang22** [comment]
And your running scripts.

**Comment by JiahuanChen** [comment]
Running into the same error. I ran the test on 4 GPUs and set TEST.IMS_PER_BATCH = 8, then I got this error. 

It seems that per GPU batch should be 1 only, thus TEST.IMS_PER_BATCH should be smaller than the number of GPUs you have.

**Comment by JiahuanChen** [comment]
> Running into the same error. I ran the test on 4 GPUs and set TEST.IMS_PER_BATCH = 8, then I got this error.
> 
> It seems that per GPU batch should be 1 only, thus TEST.IMS_PER_BATCH should be smaller than the number of GPUs you have.

Is answered here. https://github.com/zjhuang22/maskscoring_rcnn/issues/25#issuecomment-478495525

In mask head, only "result[0].get_field("mask"), result[0].get_field("labels")" is returned, which I think i limits the per GPU batch to 1.

**Comment by zhuliqian** [comment]
thanks
