### ISSUE TITLE
build error/running build_ext #

### ISSUE THREAD

**Issue by kolore** [zjhuang22/maskscoring_rcnn#39]
when i run setup.py build develop, i got this error:

copying build/lib.linux-x86_64-3.6/maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so -> maskrcnn_benchmark
error: could not create 'maskrcnn_benchmark/_C.cpython-36m-x86_64-linux-gnu.so': No such file or directory

**Comment by zjhuang22** [comment]
Have you added conda create maskrcnn_benchmark before install?

**Comment by kolore** [comment]
Oh, I haven't  done it.
