### ISSUE TITLE
The usage of mask_ratios

### ISSUE THREAD

**Issue by Retiina** [zjhuang22/maskscoring_rcnn#40]
Could anyone explain to me the meaning of `mask_ratios` and why we need to compute that? Thanks in advance. The calculation of `mask_ratios` is here:
https://github.com/zjhuang22/maskscoring_rcnn/blob/c20aa625d8f2e92a8e05c8a8307c2427b6e6015f/maskrcnn_benchmark/modeling/roi_heads/mask_head/loss.py#L76

**Comment by zjhuang22** [comment]
From mask_ration, we can get the full area of instance on the scale after roi align. And under the same scale, we can calculate the IoU between gt and prediction.

**Comment by Retiina** [comment]
We can calculate IoU directly from `mask_pred` and `mask_targets`, since they are of the same size, right?. In fact I am not clear why we need to use `mask_ratio`

**Comment by zjhuang22** [comment]
mask_target only contain parts of instance, while we need to calculate the IoU with the full instance.

**Comment by Retiina** [comment]
You are awesome sir, I finally get your point.

**Comment by zehuichen123** [comment]
I wonder the result without computing IoU with the full instance, just the cropped instance. Have you done any experiment? Intuitively, one may consider the IoU with the full instance firstly, right?

**Comment by zjhuang22** [comment]
> I wonder the result without computing IoU with the full instance, just the cropped instance. Have you done any experiment? Intuitively, one may consider the IoU with the full instance firstly, right?

The results will be a little lower.
