### ISSUE TITLE
does the performance in the `README.md` use `soft-nms`?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [zjhuang22/maskscoring_rcnn#5]

**Comment by zjhuang22** [comment]
> _No description provided._

Thanks for your attention. In this code, we only add maskiou head, other configurations are consistent with the original maskrcnn-benchmark, if maskrcnn-benchmark does not use softnms, then we do not use softnms here.

**Comment by zimenglan-sysu-512** [comment]
hi @zjhuang22 
can u share the params of soft-nms used in the paper?

**Comment by zjhuang22** [comment]
> hi @zjhuang22
> can u share the params of soft-nms used in the paper?

gaussian type, thresh 0.6

**Comment by zimenglan-sysu-512** [comment]
do u mean:  `NMS_TYPE:  Gaussian, SIGMA: 0.6, THRESHOLD: 0.001`?

**Comment by zjhuang22** [comment]
> do u mean: `NMS_TYPE: Gaussian, SIGMA: 0.6, THRESHOLD: 0.001`?

yes

**Comment by zimenglan-sysu-512** [comment]
thanks
