### ISSUE TITLE
也许是个伪课题

### ISSUE THREAD

**Issue by Kenneth-X** [zjhuang22/maskscoring_rcnn#56]
1、实例分割任务并没有用检测框分类置信度当做mask好坏的衡量标准，上面的数字只是分类的结果score。
2、训练的时候，mask R-CNN的loss中三个部分loss本身就自带了pix-level的误差，mask IOU也是由此而来的，你的iou loss本就是和3个loss中的mask loss一脉相承，换个名字而已。
3、强行在一个可视化bbox上面的score做文章，是不是有点牵强？

**Comment by jhtao1860** [comment]
@Kenneth-X  你说有可能是对的，但论文结论确实是涨点了
