### ISSUE TITLE
Multi-GPU train error

### ISSUE THREAD

**Issue by sanshibayuan** [zjhuang22/maskscoring_rcnn#58]
Hi I am facing a multi-gpu training problem and I have went through this repo and the original maskrcnn-benchmark repo and still can't solve it.

My problem is that when I train with One GPU, every thing is fine 
But when I use multi-GPU(2,3,4), I got this error 

​​​​
![image](https://user-images.githubusercontent.com/30117384/60149322-deff2680-9806-11e9-8231-ca4fce08cff9.png)

![image](https://user-images.githubusercontent.com/30117384/60149333-e45c7100-9806-11e9-972d-d4cd8e38fe6f.png)

How does this happen during multi-gpu training?  It seems to be a problem with the boxlist_op.py but I I don't think there's any fault in my code because it went GREAT when using one gpu.

Thanks A Lot !!!

**Comment by zjhuang22** [comment]
What's your running command? It seems that the problem is in the inference time. Our codes only support one image for one gpu in the inference time.
