### ISSUE TITLE
is it something wrong that the code returns only one image' label and mask in mask_head?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [zjhuang22/maskscoring_rcnn#7]
hi @zjhuang22 
i have a question that in this [line](https://github.com/zjhuang22/maskscoring_rcnn/blob/71be26f093/maskrcnn_benchmark/modeling/roi_heads/mask_head/mask_head.py#L79), it seems that it returns one image's `mask` and `label` info. if one gpu holds more than one image, how to get the corresponding `mask` and `label`?

**Comment by zimenglan-sysu-512** [comment]
and why it does not use predicted mask to compute the [target maskiou](https://github.com/zjhuang22/maskscoring_rcnn/blob/71be26f093/maskrcnn_benchmark/modeling/roi_heads/mask_head/loss.py#L46-L76)?

**Comment by zjhuang22** [comment]
> hi @zjhuang22
> i have a question that in this [line](https://github.com/zjhuang22/maskscoring_rcnn/blob/71be26f093/maskrcnn_benchmark/modeling/roi_heads/mask_head/mask_head.py#L79), it seems that it returns one image's `mask` and `label` info. if one gpu holds more than one image, how to get the corresponding `mask` and `label`?

Thanks for your attention. Our code only uses one image for one GPU during the test, without considering more than one image for one GPU during the test, which we will add later.

**Comment by zimenglan-sysu-512** [comment]
another question, why it returns `mask` instead of `selected_mask`? in that line?

**Comment by zjhuang22** [comment]
> another question, why it returns `mask` instead of `selected_mask`? in that line?

In the post-processing of mask_head, the mask has been selected according to the prediction category.

**Comment by zimenglan-sysu-512** [comment]
u are right, 
i forget it.
thanks
