### ISSUE TITLE
can u provide the training log file?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [zjhuang22/maskscoring_rcnn#8]
since i want add ur code into my own and do the trainings, so i want to reproduce ur results. can u provide the training log files?

**Comment by zimenglan-sysu-512** [comment]
in my trainings (from the starting), the `loss_maskiou` is small, like `0.0107 (0.0252)`, compared with `loss_classifier`. is it normal?

**Comment by zjhuang22** [comment]
> in my trainings (from the starting), the `loss_maskiou` is small, like `0.0107 (0.0252)`, compared with `loss_classifier`. is it normal?
> btw, i use `r50-fpn` config file.

I have updated my training log in README.md.
