### ISSUE TITLE
error when test : if 'caption' in anns[0]: IndexError: list index out of range

### ISSUE THREAD

**Issue by BudingZ** [zjhuang22/maskscoring_rcnn#89]
When I run with "configs/e2e_mask_rcnn_R_50_FPN_1x.yaml", everything is ok. But when I run with "configs/e2e_ms_rcnn_R_50_FPN_1x.yaml", error occurred. The training process has already finished, the error is to do with testing. Need your help. Thanks!

error:
Traceback (most recent call last):
File ''tools/test_net.py'' , line 94 , in<module>
    main()
File ''tools/test_net.py'', line 88,in main
   maskiou_on=cfg.MODEL.MASKI0U_ON
File ''/home/zt/github/maskscoring_rcnn-master/maskrcnn_benchmark/engine/inference.py'' , line 430 , in inference
   dataset.coco,cocoresuLls[loutype],fiLepath,loutype
File ''/home/zt/github/maskscoring_rcnn-master/maskrcnn_benchmark/engine/inference.py'',line 258,in evaluate_predictions_on_coco
   coco_dt=coco_gt.LoadRes(str(json_result_file))
File "/home/zlt/.conda/envs/maskrcnn_benchmark/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py, line 318, in LoadRes
    if 'caption' in anns[0]:
IndexError: list index out of range

**Comment by AmberrrLiu** [comment]
I suggest you looking up codes in maskrcnn_benchmark：https://github.com/facebookresearch/maskrcnn-benchmark
Compare the codes and modify it

**Comment by BudingZ** [comment]
> I suggest you looking up codes in maskrcnn_benchmark：https://github.com/facebookresearch/maskrcnn-benchmark
> Compare the codes and modify it

Thank you very much.I have solved this error,there was something wrong in my annotations file.

**Comment by TigertigerTigertiger** [comment]
I have the same issue! can you tell me whats wrong with annotations file? Thank you very much @BudingZ

**Comment by TigertigerTigertiger** [comment]
the error is to do with both testing and training

**Comment by BudingZ** [comment]
> the error is to do with both testing and training

I use VIA to make annotations but  the export json file has a bug: the segmentation has one '[ ]' (the correct format should has be '[[ ]]')  and the image_id is str(the correct format should be int). I revised json file, the error has gone.

**Comment by TigertigerTigertiger** [comment]
> > the error is to do with both testing and training
> 
> I use VIA to make annotations but the export json file has a bug: the segmentation has one '[ ]' (the correct format should has be '[[ ]]') and the image_id is str(the correct format should be int). I revised json file, the error has gone.

thanks! I'll go over the file format~
