### ISSUE TITLE
error when test: RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 10 and 38 in dimension 0 at /opt/pytorch/pytorch/aten/src/THC/generic/THCTensorMath.cu:83

### ISSUE THREAD

**Issue by KennithLi** [zjhuang22/maskscoring_rcnn#94]
I'm testing my own dataset with mask scoring rcnn. When I test my dataset with trained model weights, get errors as following:
```
Traceback (most recent call last):
  File "tools/test_net.py", line 94, in <module>
    main()
  File "tools/test_net.py", line 88, in main
    maskiou_on=cfg.MODEL.MASKIOU_ON
  File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/engine/inference.py", line 379, in inference
    predictions = compute_on_dataset(model, data_loader, device)
  File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/engine/inference.py", line 31, in compute_on_dataset
    output = model(images)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 51, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 45, in forward
    loss_maskiou, detections = self.maskiou(roi_feature, detections, selected_mask, labels, maskiou_targets)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/modeling/roi_heads/maskiou_head/maskiou_head.py", line 41, in forward
    x = self.feature_extractor(features, selected_mask)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/modeling/roi_heads/maskiou_head/roi_maskiou_feature_extractors.py", line 40, in forward
    x = torch.cat((x, mask_pool), 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 10 and 38 in dimension 0 at /opt/pytorch/pytorch/aten/src/THC/generic/THCTensorMath.cu:83
```
Then I find that the input of `x = torch.cat((x, mask_pool), 1)` in `maskrcnn_benchmark/modeling/roi_heads/maskiou_head/roi_maskiou_feature_extractors.py` with dimension 0 is different. It is result of the code in `/maskrcnn_benchmark/modeling/roi_heads/maskiou_head/maskiou_head.py`:

        if self.cfg.MODEL.MASKIOU_ON: 
            if not self.training:
                result = self.post_processor(mask_logits, proposals)
                return x, result, {}, roi_feature, result[0].get_field("mask"), result[0].get_field("labels"), None

            loss_mask, selected_mask, labels, maskiou_targets = self.loss_evaluator(proposals, mask_logits, targets)
            return x, all_proposals, dict(loss_mask=loss_mask), roi_feature, selected_mask, labels, maskiou_targets
        else:
            if not self.training:
                result = self.post_processor(mask_logits, proposals)
                return x, result, {}

As `return x, result, {}, roi_feature, result[0].get_field("mask"), result[0].get_field("labels"), None` shwon, it only returns the first item in `result` (while the 'result' is a list). I do not know the reason. Could anyone help me? Thanks a lot!

**Comment by KennithLi** [comment]
> I'm testing my own dataset with mask scoring rcnn. When I test my dataset with trained model weights, get errors as following:
> 
> ```
> Traceback (most recent call last):
>   File "tools/test_net.py", line 94, in <module>
>     main()
>   File "tools/test_net.py", line 88, in main
>     maskiou_on=cfg.MODEL.MASKIOU_ON
>   File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/engine/inference.py", line 379, in inference
>     predictions = compute_on_dataset(model, data_loader, device)
>   File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/engine/inference.py", line 31, in compute_on_dataset
>     output = model(images)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 51, in forward
>     x, result, detector_losses = self.roi_heads(features, proposals, targets)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 45, in forward
>     loss_maskiou, detections = self.maskiou(roi_feature, detections, selected_mask, labels, maskiou_targets)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/modeling/roi_heads/maskiou_head/maskiou_head.py", line 41, in forward
>     x = self.feature_extractor(features, selected_mask)
>   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/modeling/roi_heads/maskiou_head/roi_maskiou_feature_extractors.py", line 40, in forward
>     x = torch.cat((x, mask_pool), 1)
> RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 10 and 38 in dimension 0 at /opt/pytorch/pytorch/aten/src/THC/generic/THCTensorMath.cu:83
> ```
> 
> Then I find that the input of `x = torch.cat((x, mask_pool), 1)` in `maskrcnn_benchmark/modeling/roi_heads/maskiou_head/roi_maskiou_feature_extractors.py` with dimension 0 is different. It is result of the code in `/maskrcnn_benchmark/modeling/roi_heads/maskiou_head/maskiou_head.py`:
> 
> ```
>     if self.cfg.MODEL.MASKIOU_ON: 
>         if not self.training:
>             result = self.post_processor(mask_logits, proposals)
>             return x, result, {}, roi_feature, result[0].get_field("mask"), result[0].get_field("labels"), None
> 
>         loss_mask, selected_mask, labels, maskiou_targets = self.loss_evaluator(proposals, mask_logits, targets)
>         return x, all_proposals, dict(loss_mask=loss_mask), roi_feature, selected_mask, labels, maskiou_targets
>     else:
>         if not self.training:
>             result = self.post_processor(mask_logits, proposals)
>             return x, result, {}
> ```
> 
> As `return x, result, {}, roi_feature, result[0].get_field("mask"), result[0].get_field("labels"), None` shwon, it only returns the first item in `result` (while the 'result' is a list). I do not know the reason. Could anyone help me? Thanks a lot!

I solve it by modifying `/maskrcnn_benchmark/modeling/roi_heads/maskiou_head/maskiou_head.py' from
```
if self.cfg.MODEL.MASKIOU_ON: 
        if not self.training:
            result = self.post_processor(mask_logits, proposals)
            return x, result, {}, roi_feature, result[0].get_field("mask"), result[0].get_field("labels"), None
``` 
to
```
            if not self.training:
                result = self.post_processor(mask_logits, proposals)
                selected_mask = [r.get_field("mask") for r in result]
                selected_mask = torch.cat(selected_mask)
                labels = [r.get_field("labels") for r in result]
                labels = torch.cat(labels)
                # return x, result, {}, roi_feature, result[0].get_field("mask"), result[0].get_field("labels"), None
                return x, result, {}, roi_feature, selected_mask, labels, None
```
It may get error as 
```
Traceback (most recent call last):
  File "tools/test_net.py", line 94, in <module>
    main()
  File "tools/test_net.py", line 88, in main
    maskiou_on=cfg.MODEL.MASKIOU_ON
  File "/home/liqianzhong/data/maskscoring_rcnn/maskrcnn_benchmark/engine/inference.py", line 379, in inference
    predictions = compute_on_dataset(model, data_loader, device)
  File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/engine/inference.py", line 31, in compute_on_dataset
    output = model(images)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 51, in forward
    x, result, detector_losses = self.roi_heads(features, proposals, targets)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/modeling/roi_heads/roi_heads.py", line 45, in forward
    loss_maskiou, detections = self.maskiou(roi_feature, detections, selected_mask, labels, maskiou_targets)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/modeling/roi_heads/maskiou_head/maskiou_head.py", line 45, in forward
    result = self.post_processor(proposals, pred_maskiou, labels)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/li/data/maskscoring_rcnn/maskrcnn_benchmark/modeling/roi_heads/maskiou_head/inference.py", line 32, in forward
    mask_scores = bbox_scores * maskiou
RuntimeError: The size of tensor a (9) must match the size of tensor b (34) at non-singleton dimension 0
```
then replace the code in `mask scoring_rcnn/maskrcnn_benchmark/modeling/roi_heads/maskiou_head` as
```
# Mask Scoring R-CNN
# Wriiten by zhaojin.huang, 2018-12.

import numpy as np
import torch
from torch import nn
import torch.nn.functional as F

from maskrcnn_benchmark.structures.bounding_box import BoxList


# TODO get the predicted maskiou and mask score.
class MaskIoUPostProcessor(nn.Module):
    """
    Getting the maskiou according to the targeted label, and computing the mask score according to maskiou.
    """

    def __init__(self):
        super(MaskIoUPostProcessor, self).__init__()

    def forward(self, boxes, pred_maskiou, labels):
        num_masks = pred_maskiou.shape[0]
        index = torch.arange(num_masks, device=labels.device)
        maskious = pred_maskiou[index, labels]
        # split `maskiou` accroding to `boxes`
        boxes_per_image = [len(box) for box in boxes]
        maskious = maskious.split(boxes_per_image, dim=0)
        results = []
        for maskiou, box in zip(maskious, boxes):
            bbox = BoxList(box.bbox, box.size, mode="xyxy")
            for field in box.fields():
                bbox.add_field(field, box.get_field(field))
            bbox_scores = bbox.get_field("scores")
            mask_scores = bbox_scores * maskiou
            bbox.add_field("mask_scores", mask_scores)
            results.append(bbox)

        return results

def make_roi_maskiou_post_processor(cfg):
    maskiou_post_processor = MaskIoUPostProcessor()
    return maskiou_post_processor
```

**Comment by jpainam** [comment]
Hi, i have the same problem. but my `/maskrcnn_benchmark/modeling/roi_heads/maskiou_head/maskiou_head.py` looks a little bit different than yours. Here the content of  the file
```python
    def forward(self, features, proposals, selected_mask, labels, maskiou_targets=None):
        """
        Arguments:
            features (list[Tensor]): feature-maps from possibly several levels
            proposals (list[BoxList]): proposal boxes
            selected_mask (list[Tensor]): targeted mask
            labels (list[Tensor]): class label of mask
            maskiou_targets (list[Tensor], optional): the ground-truth maskiou targets.

        Returns:
            losses (dict[Tensor]): During training, returns the losses for the
                head. During testing, returns an empty dict.
            results (list[BoxList]): during training, returns None. During testing, the predicted boxlists are returned.
                with the `mask` field set
        """
        if features.shape[0] == 0 and not self.training:
            return {}, proposals

        x = self.feature_extractor(features, selected_mask)
        pred_maskiou = self.predictor(x)

        if not self.training:
            result = self.post_processor(proposals, pred_maskiou, labels)
            return {}, result

        loss_maskiou = self.loss_evaluator(labels, pred_maskiou, maskiou_targets)

        return dict(loss_maskiou=loss_maskiou), None
```
not really sure what i can change here to solve this problem. 
However, the code in `mask scoring_rcnn/maskrcnn_benchmark/modeling/roi_heads/maskiou_head` is the same as the one you reported. I can change that one.
Thanks
